// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: club.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addClubMember = `-- name: AddClubMember :one
INSERT INTO club_members (club_id, player_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (club_id, player_id) DO UPDATE SET role = club_members.role
RETURNING id, club_id, player_id, role, joined_at
`

type AddClubMemberParams struct {
	ClubID   uuid.UUID      `json:"club_id"`
	PlayerID uuid.UUID      `json:"player_id"`
	Role     ClubMemberRole `json:"role"`
}

func (q *Queries) AddClubMember(ctx context.Context, arg AddClubMemberParams) (ClubMember, error) {
	row := q.db.QueryRow(ctx, addClubMember, arg.ClubID, arg.PlayerID, arg.Role)
	var i ClubMember
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.PlayerID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const createClub = `-- name: CreateClub :one
INSERT INTO clubs (name, host_player_id, join_code)
VALUES ($1, $2, $3)
RETURNING id, name, host_player_id, join_code, created_at, updated_at
`

type CreateClubParams struct {
	Name         string    `json:"name"`
	HostPlayerID uuid.UUID `json:"host_player_id"`
	JoinCode     string    `json:"join_code"`
}

func (q *Queries) CreateClub(ctx context.Context, arg CreateClubParams) (Club, error) {
	row := q.db.QueryRow(ctx, createClub, arg.Name, arg.HostPlayerID, arg.JoinCode)
	var i Club
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HostPlayerID,
		&i.JoinCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClubByID = `-- name: GetClubByID :one
SELECT id, name, host_player_id, join_code, created_at, updated_at FROM clubs WHERE id = $1
`

func (q *Queries) GetClubByID(ctx context.Context, id uuid.UUID) (Club, error) {
	row := q.db.QueryRow(ctx, getClubByID, id)
	var i Club
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HostPlayerID,
		&i.JoinCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClubByJoinCode = `-- name: GetClubByJoinCode :one
SELECT id, name, host_player_id, join_code, created_at, updated_at FROM clubs WHERE join_code = $1
`

func (q *Queries) GetClubByJoinCode(ctx context.Context, joinCode string) (Club, error) {
	row := q.db.QueryRow(ctx, getClubByJoinCode, joinCode)
	var i Club
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HostPlayerID,
		&i.JoinCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClubMember = `-- name: GetClubMember :one
SELECT id, club_id, player_id, role, joined_at FROM club_members WHERE club_id = $1 AND player_id = $2
`

type GetClubMemberParams struct {
	ClubID   uuid.UUID `json:"club_id"`
	PlayerID uuid.UUID `json:"player_id"`
}

func (q *Queries) GetClubMember(ctx context.Context, arg GetClubMemberParams) (ClubMember, error) {
	row := q.db.QueryRow(ctx, getClubMember, arg.ClubID, arg.PlayerID)
	var i ClubMember
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.PlayerID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getClubMemberPlayerByName = `-- name: GetClubMemberPlayerByName :one
SELECT p.id, p.display_name, p.gender, p.created_at, p.updated_at, p.is_guest
FROM players p
JOIN club_members cm ON cm.player_id = p.id
WHERE cm.club_id = $1 AND lower(p.display_name) = lower($2)
ORDER BY p.created_at
LIMIT 1
`

type GetClubMemberPlayerByNameParams struct {
	ClubID uuid.UUID `json:"club_id"`
	Lower  string    `json:"lower"`
}

func (q *Queries) GetClubMemberPlayerByName(ctx context.Context, arg GetClubMemberPlayerByNameParams) (Player, error) {
	row := q.db.QueryRow(ctx, getClubMemberPlayerByName, arg.ClubID, arg.Lower)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Gender,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsGuest,
	)
	return i, err
}

const listClubMembers = `-- name: ListClubMembers :many
SELECT id, club_id, player_id, role, joined_at FROM club_members WHERE club_id = $1 ORDER BY joined_at
`

func (q *Queries) ListClubMembers(ctx context.Context, clubID uuid.UUID) ([]ClubMember, error) {
	rows, err := q.db.Query(ctx, listClubMembers, clubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClubMember{}
	for rows.Next() {
		var i ClubMember
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.PlayerID,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClubMemberRole = `-- name: UpdateClubMemberRole :one
UPDATE club_members SET role = $3
WHERE club_id = $1 AND player_id = $2
RETURNING id, club_id, player_id, role, joined_at
`

type UpdateClubMemberRoleParams struct {
	ClubID   uuid.UUID      `json:"club_id"`
	PlayerID uuid.UUID      `json:"player_id"`
	Role     ClubMemberRole `json:"role"`
}

func (q *Queries) UpdateClubMemberRole(ctx context.Context, arg UpdateClubMemberRoleParams) (ClubMember, error) {
	row := q.db.QueryRow(ctx, updateClubMemberRole, arg.ClubID, arg.PlayerID, arg.Role)
	var i ClubMember
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.PlayerID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}
