// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: match.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addMatchPlayer = `-- name: AddMatchPlayer :one
INSERT INTO match_players (match_id, player_id, team, rating_before)
VALUES ($1, $2, $3, $4)
RETURNING match_id, player_id, team, rating_before, rating_after, rating_change
`

type AddMatchPlayerParams struct {
	MatchID      uuid.UUID     `json:"match_id"`
	PlayerID     uuid.UUID     `json:"player_id"`
	Team         MatchTeam     `json:"team"`
	RatingBefore pgtype.Float8 `json:"rating_before"`
}

func (q *Queries) AddMatchPlayer(ctx context.Context, arg AddMatchPlayerParams) (MatchPlayer, error) {
	row := q.db.QueryRow(ctx, addMatchPlayer,
		arg.MatchID,
		arg.PlayerID,
		arg.Team,
		arg.RatingBefore,
	)
	var i MatchPlayer
	err := row.Scan(
		&i.MatchID,
		&i.PlayerID,
		&i.Team,
		&i.RatingBefore,
		&i.RatingAfter,
		&i.RatingChange,
	)
	return i, err
}

const createMatch = `-- name: CreateMatch :one
INSERT INTO matches (session_id, court_id, format)
VALUES ($1, $2, $3)
RETURNING id, session_id, court_id, format, status, started_at, ended_at, score_a, score_b, winner, created_at, updated_at
`

type CreateMatchParams struct {
	SessionID uuid.UUID   `json:"session_id"`
	CourtID   uuid.UUID   `json:"court_id"`
	Format    MatchFormat `json:"format"`
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, createMatch, arg.SessionID, arg.CourtID, arg.Format)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CourtID,
		&i.Format,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.ScoreA,
		&i.ScoreB,
		&i.Winner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const finishMatch = `-- name: FinishMatch :one
UPDATE matches
SET status = 'FINISHED', ended_at = now(), score_a = $2, score_b = $3, winner = $4, updated_at = now()
WHERE id = $1
RETURNING id, session_id, court_id, format, status, started_at, ended_at, score_a, score_b, winner, created_at, updated_at
`

type FinishMatchParams struct {
	ID     uuid.UUID       `json:"id"`
	ScoreA pgtype.Int4     `json:"score_a"`
	ScoreB pgtype.Int4     `json:"score_b"`
	Winner NullMatchWinner `json:"winner"`
}

func (q *Queries) FinishMatch(ctx context.Context, arg FinishMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, finishMatch,
		arg.ID,
		arg.ScoreA,
		arg.ScoreB,
		arg.Winner,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CourtID,
		&i.Format,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.ScoreA,
		&i.ScoreB,
		&i.Winner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMatchByID = `-- name: GetMatchByID :one
SELECT id, session_id, court_id, format, status, started_at, ended_at, score_a, score_b, winner, created_at, updated_at FROM matches WHERE id = $1
`

func (q *Queries) GetMatchByID(ctx context.Context, id uuid.UUID) (Match, error) {
	row := q.db.QueryRow(ctx, getMatchByID, id)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CourtID,
		&i.Format,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.ScoreA,
		&i.ScoreB,
		&i.Winner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMatchPlayers = `-- name: ListMatchPlayers :many
SELECT match_id, player_id, team, rating_before, rating_after, rating_change FROM match_players WHERE match_id = $1
`

func (q *Queries) ListMatchPlayers(ctx context.Context, matchID uuid.UUID) ([]MatchPlayer, error) {
	rows, err := q.db.Query(ctx, listMatchPlayers, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MatchPlayer{}
	for rows.Next() {
		var i MatchPlayer
		if err := rows.Scan(
			&i.MatchID,
			&i.PlayerID,
			&i.Team,
			&i.RatingBefore,
			&i.RatingAfter,
			&i.RatingChange,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchesBySession = `-- name: ListMatchesBySession :many
SELECT id, session_id, court_id, format, status, started_at, ended_at, score_a, score_b, winner, created_at, updated_at FROM matches WHERE session_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListMatchesBySession(ctx context.Context, sessionID uuid.UUID) ([]Match, error) {
	rows, err := q.db.Query(ctx, listMatchesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Match{}
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.CourtID,
			&i.Format,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.ScoreA,
			&i.ScoreB,
			&i.Winner,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMatchByID = `-- name: LockMatchByID :one
SELECT id, session_id, court_id, format, status, started_at, ended_at, score_a, score_b, winner, created_at, updated_at FROM matches WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockMatchByID(ctx context.Context, id uuid.UUID) (Match, error) {
	row := q.db.QueryRow(ctx, lockMatchByID, id)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CourtID,
		&i.Format,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.ScoreA,
		&i.ScoreB,
		&i.Winner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setMatchPlayerRatingAfter = `-- name: SetMatchPlayerRatingAfter :one
UPDATE match_players
SET rating_after = $3, rating_change = $4
WHERE match_id = $1 AND player_id = $2
RETURNING match_id, player_id, team, rating_before, rating_after, rating_change
`

type SetMatchPlayerRatingAfterParams struct {
	MatchID      uuid.UUID     `json:"match_id"`
	PlayerID     uuid.UUID     `json:"player_id"`
	RatingAfter  pgtype.Float8 `json:"rating_after"`
	RatingChange pgtype.Float8 `json:"rating_change"`
}

func (q *Queries) SetMatchPlayerRatingAfter(ctx context.Context, arg SetMatchPlayerRatingAfterParams) (MatchPlayer, error) {
	row := q.db.QueryRow(ctx, setMatchPlayerRatingAfter,
		arg.MatchID,
		arg.PlayerID,
		arg.RatingAfter,
		arg.RatingChange,
	)
	var i MatchPlayer
	err := row.Scan(
		&i.MatchID,
		&i.PlayerID,
		&i.Team,
		&i.RatingBefore,
		&i.RatingAfter,
		&i.RatingChange,
	)
	return i, err
}

const startMatch = `-- name: StartMatch :one
UPDATE matches
SET status = 'PLAYING', started_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, session_id, court_id, format, status, started_at, ended_at, score_a, score_b, winner, created_at, updated_at
`

func (q *Queries) StartMatch(ctx context.Context, id uuid.UUID) (Match, error) {
	row := q.db.QueryRow(ctx, startMatch, id)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CourtID,
		&i.Format,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.ScoreA,
		&i.ScoreB,
		&i.Winner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
