// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ClubMemberRole string

const (
	ClubMemberRoleHOST   ClubMemberRole = "HOST"
	ClubMemberRolePLAYER ClubMemberRole = "PLAYER"
)

func (e *ClubMemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ClubMemberRole(s)
	case string:
		*e = ClubMemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for ClubMemberRole: %T", src)
	}
	return nil
}

type NullClubMemberRole struct {
	ClubMemberRole ClubMemberRole `json:"club_member_role"`
	Valid          bool           `json:"valid"` // Valid is true if ClubMemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullClubMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.ClubMemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ClubMemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullClubMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ClubMemberRole), nil
}

type CourtStatus string

const (
	CourtStatusAVAILABLE CourtStatus = "AVAILABLE"
	CourtStatusPLAYING   CourtStatus = "PLAYING"
)

func (e *CourtStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CourtStatus(s)
	case string:
		*e = CourtStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CourtStatus: %T", src)
	}
	return nil
}

type NullCourtStatus struct {
	CourtStatus CourtStatus `json:"court_status"`
	Valid       bool        `json:"valid"` // Valid is true if CourtStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCourtStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CourtStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CourtStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCourtStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CourtStatus), nil
}

type MatchFormat string

const (
	MatchFormatMIXEDDOUBLES MatchFormat = "MIXED_DOUBLES"
	MatchFormatMENDOUBLES   MatchFormat = "MEN_DOUBLES"
	MatchFormatWOMENDOUBLES MatchFormat = "WOMEN_DOUBLES"
)

func (e *MatchFormat) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MatchFormat(s)
	case string:
		*e = MatchFormat(s)
	default:
		return fmt.Errorf("unsupported scan type for MatchFormat: %T", src)
	}
	return nil
}

type NullMatchFormat struct {
	MatchFormat MatchFormat `json:"match_format"`
	Valid       bool        `json:"valid"` // Valid is true if MatchFormat is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMatchFormat) Scan(value interface{}) error {
	if value == nil {
		ns.MatchFormat, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MatchFormat.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMatchFormat) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MatchFormat), nil
}

type MatchStatus string

const (
	MatchStatusCREATED  MatchStatus = "CREATED"
	MatchStatusPLAYING  MatchStatus = "PLAYING"
	MatchStatusFINISHED MatchStatus = "FINISHED"
)

func (e *MatchStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MatchStatus(s)
	case string:
		*e = MatchStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MatchStatus: %T", src)
	}
	return nil
}

type NullMatchStatus struct {
	MatchStatus MatchStatus `json:"match_status"`
	Valid       bool        `json:"valid"` // Valid is true if MatchStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMatchStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MatchStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MatchStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMatchStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MatchStatus), nil
}

type MatchTeam string

const (
	MatchTeamA MatchTeam = "A"
	MatchTeamB MatchTeam = "B"
)

func (e *MatchTeam) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MatchTeam(s)
	case string:
		*e = MatchTeam(s)
	default:
		return fmt.Errorf("unsupported scan type for MatchTeam: %T", src)
	}
	return nil
}

type NullMatchTeam struct {
	MatchTeam MatchTeam `json:"match_team"`
	Valid     bool      `json:"valid"` // Valid is true if MatchTeam is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMatchTeam) Scan(value interface{}) error {
	if value == nil {
		ns.MatchTeam, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MatchTeam.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMatchTeam) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MatchTeam), nil
}

type MatchWinner string

const (
	MatchWinnerA MatchWinner = "A"
	MatchWinnerB MatchWinner = "B"
)

func (e *MatchWinner) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MatchWinner(s)
	case string:
		*e = MatchWinner(s)
	default:
		return fmt.Errorf("unsupported scan type for MatchWinner: %T", src)
	}
	return nil
}

type NullMatchWinner struct {
	MatchWinner MatchWinner `json:"match_winner"`
	Valid       bool        `json:"valid"` // Valid is true if MatchWinner is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMatchWinner) Scan(value interface{}) error {
	if value == nil {
		ns.MatchWinner, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MatchWinner.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMatchWinner) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MatchWinner), nil
}

type PlayerGender string

const (
	PlayerGenderMALE   PlayerGender = "MALE"
	PlayerGenderFEMALE PlayerGender = "FEMALE"
)

func (e *PlayerGender) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlayerGender(s)
	case string:
		*e = PlayerGender(s)
	default:
		return fmt.Errorf("unsupported scan type for PlayerGender: %T", src)
	}
	return nil
}

type NullPlayerGender struct {
	PlayerGender PlayerGender `json:"player_gender"`
	Valid        bool         `json:"valid"` // Valid is true if PlayerGender is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlayerGender) Scan(value interface{}) error {
	if value == nil {
		ns.PlayerGender, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlayerGender.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlayerGender) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlayerGender), nil
}

type SessionAssignmentMode string

const (
	SessionAssignmentModeAUTOMATIC SessionAssignmentMode = "AUTOMATIC"
	SessionAssignmentModeMANUAL    SessionAssignmentMode = "MANUAL"
)

func (e *SessionAssignmentMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionAssignmentMode(s)
	case string:
		*e = SessionAssignmentMode(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionAssignmentMode: %T", src)
	}
	return nil
}

type NullSessionAssignmentMode struct {
	SessionAssignmentMode SessionAssignmentMode `json:"session_assignment_mode"`
	Valid                 bool                  `json:"valid"` // Valid is true if SessionAssignmentMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionAssignmentMode) Scan(value interface{}) error {
	if value == nil {
		ns.SessionAssignmentMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionAssignmentMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionAssignmentMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionAssignmentMode), nil
}

type SessionPlayerStatus string

const (
	SessionPlayerStatusWAITING SessionPlayerStatus = "WAITING"
	SessionPlayerStatusPLAYING SessionPlayerStatus = "PLAYING"
	SessionPlayerStatusBREAK   SessionPlayerStatus = "BREAK"
	SessionPlayerStatusENDED   SessionPlayerStatus = "ENDED"
)

func (e *SessionPlayerStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionPlayerStatus(s)
	case string:
		*e = SessionPlayerStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionPlayerStatus: %T", src)
	}
	return nil
}

type NullSessionPlayerStatus struct {
	SessionPlayerStatus SessionPlayerStatus `json:"session_player_status"`
	Valid               bool                `json:"valid"` // Valid is true if SessionPlayerStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionPlayerStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SessionPlayerStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionPlayerStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionPlayerStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionPlayerStatus), nil
}

type SessionStatus string

const (
	SessionStatusNOTSTARTED SessionStatus = "NOT_STARTED"
	SessionStatusACTIVE     SessionStatus = "ACTIVE"
	SessionStatusFINISHED   SessionStatus = "FINISHED"
)

func (e *SessionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionStatus(s)
	case string:
		*e = SessionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionStatus: %T", src)
	}
	return nil
}

type NullSessionStatus struct {
	SessionStatus SessionStatus `json:"session_status"`
	Valid         bool          `json:"valid"` // Valid is true if SessionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SessionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionStatus), nil
}

type Club struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	HostPlayerID uuid.UUID          `json:"host_player_id"`
	JoinCode     string             `json:"join_code"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ClubMember struct {
	ID       uuid.UUID          `json:"id"`
	ClubID   uuid.UUID          `json:"club_id"`
	PlayerID uuid.UUID          `json:"player_id"`
	Role     ClubMemberRole     `json:"role"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type Court struct {
	ID        uuid.UUID          `json:"id"`
	SessionID uuid.UUID          `json:"session_id"`
	Name      string             `json:"name"`
	Status    CourtStatus        `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Match struct {
	ID        uuid.UUID          `json:"id"`
	SessionID uuid.UUID          `json:"session_id"`
	CourtID   uuid.UUID          `json:"court_id"`
	Format    MatchFormat        `json:"format"`
	Status    MatchStatus        `json:"status"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
	EndedAt   pgtype.Timestamptz `json:"ended_at"`
	ScoreA    pgtype.Int4        `json:"score_a"`
	ScoreB    pgtype.Int4        `json:"score_b"`
	Winner    NullMatchWinner    `json:"winner"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type MatchPlayer struct {
	MatchID      uuid.UUID     `json:"match_id"`
	PlayerID     uuid.UUID     `json:"player_id"`
	Team         MatchTeam     `json:"team"`
	RatingBefore pgtype.Float8 `json:"rating_before"`
	RatingAfter  pgtype.Float8 `json:"rating_after"`
	RatingChange pgtype.Float8 `json:"rating_change"`
}

type Player struct {
	ID          uuid.UUID          `json:"id"`
	DisplayName string             `json:"display_name"`
	Gender      PlayerGender       `json:"gender"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	IsGuest     bool               `json:"is_guest"`
}

type PlayerRating struct {
	PlayerID  uuid.UUID          `json:"player_id"`
	Rating    float64            `json:"rating"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type PlayerToken struct {
	ID        uuid.UUID          `json:"id"`
	PlayerID  uuid.UUID          `json:"player_id"`
	TokenHash string             `json:"token_hash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type RatingHistory struct {
	ID           uuid.UUID          `json:"id"`
	PlayerID     uuid.UUID          `json:"player_id"`
	MatchID      uuid.UUID          `json:"match_id"`
	RatingBefore float64            `json:"rating_before"`
	RatingAfter  float64            `json:"rating_after"`
	RatingChange float64            `json:"rating_change"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID              uuid.UUID             `json:"id"`
	ClubID          uuid.UUID             `json:"club_id"`
	Name            string                `json:"name"`
	Status          SessionStatus         `json:"status"`
	AssignmentMode  SessionAssignmentMode `json:"assignment_mode"`
	StartedAt       pgtype.Timestamptz    `json:"started_at"`
	EndedAt         pgtype.Timestamptz    `json:"ended_at"`
	CreatedAt       pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz    `json:"updated_at"`
	AutoFillEnabled bool                  `json:"auto_fill_enabled"`
}

type SessionPlayer struct {
	ID                        uuid.UUID           `json:"id"`
	SessionID                 uuid.UUID           `json:"session_id"`
	PlayerID                  uuid.UUID           `json:"player_id"`
	Status                    SessionPlayerStatus `json:"status"`
	WaitingStartedAt          pgtype.Timestamptz  `json:"waiting_started_at"`
	AccumulatedWaitingSeconds int64               `json:"accumulated_waiting_seconds"`
	MatchesPlayed             int32               `json:"matches_played"`
	Wins                      int32               `json:"wins"`
	Losses                    int32               `json:"losses"`
	CreatedAt                 pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz  `json:"updated_at"`
}
