// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: player.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createGuestPlayer = `-- name: CreateGuestPlayer :one
INSERT INTO players (display_name, gender, is_guest)
VALUES ($1, $2, true)
RETURNING id, display_name, gender, created_at, updated_at, is_guest
`

type CreateGuestPlayerParams struct {
	DisplayName string       `json:"display_name"`
	Gender      PlayerGender `json:"gender"`
}

func (q *Queries) CreateGuestPlayer(ctx context.Context, arg CreateGuestPlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, createGuestPlayer, arg.DisplayName, arg.Gender)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Gender,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsGuest,
	)
	return i, err
}

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (display_name, gender)
VALUES ($1, $2)
RETURNING id, display_name, gender, created_at, updated_at, is_guest
`

type CreatePlayerParams struct {
	DisplayName string       `json:"display_name"`
	Gender      PlayerGender `json:"gender"`
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, createPlayer, arg.DisplayName, arg.Gender)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Gender,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsGuest,
	)
	return i, err
}

const createPlayerRating = `-- name: CreatePlayerRating :one
INSERT INTO player_ratings (player_id, rating)
VALUES ($1, $2)
RETURNING player_id, rating, updated_at
`

type CreatePlayerRatingParams struct {
	PlayerID uuid.UUID `json:"player_id"`
	Rating   float64   `json:"rating"`
}

func (q *Queries) CreatePlayerRating(ctx context.Context, arg CreatePlayerRatingParams) (PlayerRating, error) {
	row := q.db.QueryRow(ctx, createPlayerRating, arg.PlayerID, arg.Rating)
	var i PlayerRating
	err := row.Scan(&i.PlayerID, &i.Rating, &i.UpdatedAt)
	return i, err
}

const createPlayerToken = `-- name: CreatePlayerToken :one
INSERT INTO player_tokens (player_id, token_hash)
VALUES ($1, $2)
RETURNING id, player_id, token_hash, created_at, revoked_at
`

type CreatePlayerTokenParams struct {
	PlayerID  uuid.UUID `json:"player_id"`
	TokenHash string    `json:"token_hash"`
}

func (q *Queries) CreatePlayerToken(ctx context.Context, arg CreatePlayerTokenParams) (PlayerToken, error) {
	row := q.db.QueryRow(ctx, createPlayerToken, arg.PlayerID, arg.TokenHash)
	var i PlayerToken
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const deleteStaleGuests = `-- name: DeleteStaleGuests :many
DELETE FROM players
WHERE is_guest
  AND updated_at < $1::timestamptz
  AND NOT EXISTS (
    SELECT 1
    FROM session_players sp
    JOIN sessions s ON s.id = sp.session_id
    WHERE sp.player_id = players.id
      AND s.status IN ('NOT_STARTED', 'ACTIVE')
  )
RETURNING id
`

// match_players.player_id and session_players.player_id both ON DELETE SET
// NULL (see migration 000001), so deleting the guest here preserves the
// match/session history it took part in (score, team, rating deltas,
// session roster slot) and only clears the link back to its identity.
// rating_history, player_ratings, club_members and player_tokens still
// cascade away — those are the guest's own state/ledger, not match/session
// history, and the guest is gone anyway.
func (q *Queries) DeleteStaleGuests(ctx context.Context, cutoff pgtype.Timestamptz) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, deleteStaleGuests, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayer = `-- name: GetPlayer :one
SELECT id, display_name, gender, created_at, updated_at, is_guest FROM players WHERE id = $1
`

func (q *Queries) GetPlayer(ctx context.Context, id uuid.UUID) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayer, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Gender,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsGuest,
	)
	return i, err
}

const getPlayerByTokenHash = `-- name: GetPlayerByTokenHash :one
SELECT p.id, p.display_name, p.gender, p.created_at, p.updated_at, p.is_guest
FROM players p
JOIN player_tokens t ON t.player_id = p.id
WHERE t.token_hash = $1 AND t.revoked_at IS NULL
`

func (q *Queries) GetPlayerByTokenHash(ctx context.Context, tokenHash string) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayerByTokenHash, tokenHash)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Gender,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsGuest,
	)
	return i, err
}

const getPlayerRating = `-- name: GetPlayerRating :one
SELECT player_id, rating, updated_at FROM player_ratings WHERE player_id = $1
`

func (q *Queries) GetPlayerRating(ctx context.Context, playerID uuid.UUID) (PlayerRating, error) {
	row := q.db.QueryRow(ctx, getPlayerRating, playerID)
	var i PlayerRating
	err := row.Scan(&i.PlayerID, &i.Rating, &i.UpdatedAt)
	return i, err
}

const getPlayerRatingsByIDs = `-- name: GetPlayerRatingsByIDs :many
SELECT player_id, rating, updated_at FROM player_ratings
WHERE player_id = ANY($1::uuid[])
`

func (q *Queries) GetPlayerRatingsByIDs(ctx context.Context, playerIds []uuid.UUID) ([]PlayerRating, error) {
	rows, err := q.db.Query(ctx, getPlayerRatingsByIDs, playerIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlayerRating{}
	for rows.Next() {
		var i PlayerRating
		if err := rows.Scan(&i.PlayerID, &i.Rating, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayersByIDs = `-- name: GetPlayersByIDs :many
SELECT id, display_name, gender, created_at, updated_at, is_guest FROM players
WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetPlayersByIDs(ctx context.Context, playerIds []uuid.UUID) ([]Player, error) {
	rows, err := q.db.Query(ctx, getPlayersByIDs, playerIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Player{}
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Gender,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsGuest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRatingHistory = `-- name: InsertRatingHistory :one
INSERT INTO rating_history (player_id, match_id, rating_before, rating_after, rating_change)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, player_id, match_id, rating_before, rating_after, rating_change, created_at
`

type InsertRatingHistoryParams struct {
	PlayerID     uuid.UUID `json:"player_id"`
	MatchID      uuid.UUID `json:"match_id"`
	RatingBefore float64   `json:"rating_before"`
	RatingAfter  float64   `json:"rating_after"`
	RatingChange float64   `json:"rating_change"`
}

func (q *Queries) InsertRatingHistory(ctx context.Context, arg InsertRatingHistoryParams) (RatingHistory, error) {
	row := q.db.QueryRow(ctx, insertRatingHistory,
		arg.PlayerID,
		arg.MatchID,
		arg.RatingBefore,
		arg.RatingAfter,
		arg.RatingChange,
	)
	var i RatingHistory
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.MatchID,
		&i.RatingBefore,
		&i.RatingAfter,
		&i.RatingChange,
		&i.CreatedAt,
	)
	return i, err
}

const listMatchesByPlayer = `-- name: ListMatchesByPlayer :many
SELECT m.id, m.session_id, m.court_id, m.format, m.status, m.started_at, m.ended_at, m.score_a, m.score_b, m.winner, m.created_at, m.updated_at
FROM matches m
JOIN match_players mp ON mp.match_id = m.id
WHERE mp.player_id = $1::uuid
ORDER BY m.created_at DESC
LIMIT $3 OFFSET $2
`

type ListMatchesByPlayerParams struct {
	PlayerID  uuid.UUID `json:"player_id"`
	RowOffset int32     `json:"row_offset"`
	RowLimit  int32     `json:"row_limit"`
}

// player_id is cast explicitly because match_players.player_id is nullable
// (see migration 000001); listing a specific player's matches always looks
// up a real player, so keep the parameter typed as a plain, non-nullable
// uuid.
func (q *Queries) ListMatchesByPlayer(ctx context.Context, arg ListMatchesByPlayerParams) ([]Match, error) {
	rows, err := q.db.Query(ctx, listMatchesByPlayer, arg.PlayerID, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Match{}
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.CourtID,
			&i.Format,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.ScoreA,
			&i.ScoreB,
			&i.Winner,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRatingHistoryByPlayer = `-- name: ListRatingHistoryByPlayer :many
SELECT id, player_id, match_id, rating_before, rating_after, rating_change, created_at FROM rating_history
WHERE player_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListRatingHistoryByPlayerParams struct {
	PlayerID uuid.UUID `json:"player_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListRatingHistoryByPlayer(ctx context.Context, arg ListRatingHistoryByPlayerParams) ([]RatingHistory, error) {
	rows, err := q.db.Query(ctx, listRatingHistoryByPlayer, arg.PlayerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RatingHistory{}
	for rows.Next() {
		var i RatingHistory
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.MatchID,
			&i.RatingBefore,
			&i.RatingAfter,
			&i.RatingChange,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPlayerRatingsByIDs = `-- name: LockPlayerRatingsByIDs :many
SELECT player_id, rating, updated_at FROM player_ratings
WHERE player_id = ANY($1::uuid[])
ORDER BY player_id
FOR UPDATE
`

func (q *Queries) LockPlayerRatingsByIDs(ctx context.Context, playerIds []uuid.UUID) ([]PlayerRating, error) {
	rows, err := q.db.Query(ctx, lockPlayerRatingsByIDs, playerIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlayerRating{}
	for rows.Next() {
		var i PlayerRating
		if err := rows.Scan(&i.PlayerID, &i.Rating, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlayerProfile = `-- name: UpdatePlayerProfile :one
UPDATE players
SET display_name = $2, gender = $3, updated_at = now()
WHERE id = $1
RETURNING id, display_name, gender, created_at, updated_at, is_guest
`

type UpdatePlayerProfileParams struct {
	ID          uuid.UUID    `json:"id"`
	DisplayName string       `json:"display_name"`
	Gender      PlayerGender `json:"gender"`
}

func (q *Queries) UpdatePlayerProfile(ctx context.Context, arg UpdatePlayerProfileParams) (Player, error) {
	row := q.db.QueryRow(ctx, updatePlayerProfile, arg.ID, arg.DisplayName, arg.Gender)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Gender,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsGuest,
	)
	return i, err
}

const updatePlayerRating = `-- name: UpdatePlayerRating :one
UPDATE player_ratings
SET rating = $2, updated_at = now()
WHERE player_id = $1
RETURNING player_id, rating, updated_at
`

type UpdatePlayerRatingParams struct {
	PlayerID uuid.UUID `json:"player_id"`
	Rating   float64   `json:"rating"`
}

func (q *Queries) UpdatePlayerRating(ctx context.Context, arg UpdatePlayerRatingParams) (PlayerRating, error) {
	row := q.db.QueryRow(ctx, updatePlayerRating, arg.PlayerID, arg.Rating)
	var i PlayerRating
	err := row.Scan(&i.PlayerID, &i.Rating, &i.UpdatedAt)
	return i, err
}
