// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddClubMember(ctx context.Context, arg AddClubMemberParams) (ClubMember, error)
	// player_id is cast explicitly because the column is nullable (see
	// migration 000001 — cleared via ON DELETE SET NULL when a guest is later
	// deleted); a live match is always assigned a real player, so keep the
	// parameter typed as a plain, non-nullable uuid.
	AddMatchPlayer(ctx context.Context, arg AddMatchPlayerParams) (MatchPlayer, error)
	// ============================================================
	// Session players
	// ============================================================
	// player_id is cast explicitly because the column is nullable (see
	// migration 000001 — cleared via ON DELETE SET NULL when a guest is later
	// deleted); joining a session always assigns a real player, so keep the
	// parameter typed as a plain, non-nullable uuid.
	AddSessionPlayer(ctx context.Context, arg AddSessionPlayerParams) (SessionPlayer, error)
	// Read-only headcount used by the auto-fill background job to decide how
	// many of a session's AVAILABLE courts it can fill this tick; the
	// authoritative check happens inside GenerateAutomatic's own FOR UPDATE
	// transaction.
	CountWaitingSessionPlayers(ctx context.Context, sessionID uuid.UUID) (int64, error)
	CreateClub(ctx context.Context, arg CreateClubParams) (Club, error)
	// ============================================================
	// Courts
	// ============================================================
	CreateCourt(ctx context.Context, arg CreateCourtParams) (Court, error)
	CreateGuestPlayer(ctx context.Context, arg CreateGuestPlayerParams) (Player, error)
	CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error)
	CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error)
	CreatePlayerRating(ctx context.Context, arg CreatePlayerRatingParams) (PlayerRating, error)
	CreatePlayerToken(ctx context.Context, arg CreatePlayerTokenParams) (PlayerToken, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// match_players.player_id and session_players.player_id both ON DELETE SET
	// NULL (see migration 000001), so deleting the guest here preserves the
	// match/session history it took part in (score, team, rating deltas,
	// session roster slot) and only clears the link back to its identity.
	// rating_history, player_ratings, club_members and player_tokens still
	// cascade away — those are the guest's own state/ledger, not match/session
	// history, and the guest is gone anyway.
	DeleteStaleGuests(ctx context.Context, cutoff pgtype.Timestamptz) ([]uuid.UUID, error)
	EndSession(ctx context.Context, id uuid.UUID) (Session, error)
	FinishMatch(ctx context.Context, arg FinishMatchParams) (Match, error)
	GetClubByID(ctx context.Context, id uuid.UUID) (Club, error)
	GetClubByJoinCode(ctx context.Context, joinCode string) (Club, error)
	GetClubMember(ctx context.Context, arg GetClubMemberParams) (ClubMember, error)
	GetClubMemberPlayerByName(ctx context.Context, arg GetClubMemberPlayerByNameParams) (Player, error)
	GetCourtByID(ctx context.Context, id uuid.UUID) (Court, error)
	GetMatchByID(ctx context.Context, id uuid.UUID) (Match, error)
	GetPlayer(ctx context.Context, id uuid.UUID) (Player, error)
	GetPlayerByTokenHash(ctx context.Context, tokenHash string) (Player, error)
	GetPlayerRating(ctx context.Context, playerID uuid.UUID) (PlayerRating, error)
	GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error)
	GetSessionPlayer(ctx context.Context, id uuid.UUID) (SessionPlayer, error)
	GetSessionPlayerBySessionAndPlayer(ctx context.Context, arg GetSessionPlayerBySessionAndPlayerParams) (SessionPlayer, error)
	GetSessionPlayerBySessionAndPlayerForUpdate(ctx context.Context, arg GetSessionPlayerBySessionAndPlayerForUpdateParams) (SessionPlayer, error)
	IncrementSessionPlayerMatchStats(ctx context.Context, arg IncrementSessionPlayerMatchStatsParams) (SessionPlayer, error)
	InsertRatingHistory(ctx context.Context, arg InsertRatingHistoryParams) (RatingHistory, error)
	// Sessions eligible for the fully-automatic auto-fill background job: ACTIVE,
	// AUTOMATIC assignment, and auto_fill_enabled. Read-only (no locking) — the
	// job's per-session coordination lock and match.Service.GenerateAutomatic's
	// own transactional locking handle correctness.
	ListActiveAutoFillSessions(ctx context.Context) ([]Session, error)
	ListAvailableCourtsBySession(ctx context.Context, sessionID uuid.UUID) ([]Court, error)
	ListClubMembers(ctx context.Context, clubID uuid.UUID) ([]ClubMember, error)
	ListCourtsBySession(ctx context.Context, sessionID uuid.UUID) ([]Court, error)
	ListMatchPlayers(ctx context.Context, matchID uuid.UUID) ([]MatchPlayer, error)
	// player_id is cast explicitly because match_players.player_id is nullable
	// (see migration 000001); listing a specific player's matches always looks
	// up a real player, so keep the parameter typed as a plain, non-nullable
	// uuid.
	ListMatchesByPlayer(ctx context.Context, arg ListMatchesByPlayerParams) ([]Match, error)
	ListMatchesBySession(ctx context.Context, sessionID uuid.UUID) ([]Match, error)
	ListRatingHistoryByPlayer(ctx context.Context, arg ListRatingHistoryByPlayerParams) ([]RatingHistory, error)
	ListSessionPlayers(ctx context.Context, sessionID uuid.UUID) ([]SessionPlayer, error)
	ListSessionsByClub(ctx context.Context, clubID uuid.UUID) ([]Session, error)
	// Eligible players for matchmaking, locked to serialize concurrent match generation.
	ListWaitingSessionPlayersForUpdate(ctx context.Context, sessionID uuid.UUID) ([]SessionPlayer, error)
	LockAvailableCourtForUpdate(ctx context.Context, id uuid.UUID) (Court, error)
	LockCourtByID(ctx context.Context, id uuid.UUID) (Court, error)
	LockMatchByID(ctx context.Context, id uuid.UUID) (Match, error)
	LockPlayerRatingsByIDs(ctx context.Context, playerIds []uuid.UUID) ([]PlayerRating, error)
	LockSessionByID(ctx context.Context, id uuid.UUID) (Session, error)
	LockSessionPlayersByIDs(ctx context.Context, ids []uuid.UUID) ([]SessionPlayer, error)
	SetCourtStatus(ctx context.Context, arg SetCourtStatusParams) (Court, error)
	SetMatchPlayerRatingAfter(ctx context.Context, arg SetMatchPlayerRatingAfterParams) (MatchPlayer, error)
	SetSessionPlayerStatus(ctx context.Context, arg SetSessionPlayerStatusParams) (SessionPlayer, error)
	StartMatch(ctx context.Context, id uuid.UUID) (Match, error)
	StartSession(ctx context.Context, id uuid.UUID) (Session, error)
	UpdateClubMemberRole(ctx context.Context, arg UpdateClubMemberRoleParams) (ClubMember, error)
	UpdatePlayerProfile(ctx context.Context, arg UpdatePlayerProfileParams) (Player, error)
	UpdatePlayerRating(ctx context.Context, arg UpdatePlayerRatingParams) (PlayerRating, error)
	UpdateSessionAssignmentMode(ctx context.Context, arg UpdateSessionAssignmentModeParams) (Session, error)
	UpdateSessionAutoFillEnabled(ctx context.Context, arg UpdateSessionAutoFillEnabledParams) (Session, error)
}

var _ Querier = (*Queries)(nil)
