// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addSessionPlayer = `-- name: AddSessionPlayer :one

INSERT INTO session_players (session_id, player_id)
VALUES ($1, $2::uuid)
ON CONFLICT (session_id, player_id) DO UPDATE SET session_id = session_players.session_id
RETURNING id, session_id, player_id, status, waiting_started_at, accumulated_waiting_seconds, matches_played, wins, losses, created_at, updated_at
`

type AddSessionPlayerParams struct {
	SessionID uuid.UUID `json:"session_id"`
	PlayerID  uuid.UUID `json:"player_id"`
}

// ============================================================
// Session players
// ============================================================
// player_id is cast explicitly because the column is nullable (see
// migration 000001 — cleared via ON DELETE SET NULL when a guest is later
// deleted); joining a session always assigns a real player, so keep the
// parameter typed as a plain, non-nullable uuid.
func (q *Queries) AddSessionPlayer(ctx context.Context, arg AddSessionPlayerParams) (SessionPlayer, error) {
	row := q.db.QueryRow(ctx, addSessionPlayer, arg.SessionID, arg.PlayerID)
	var i SessionPlayer
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.PlayerID,
		&i.Status,
		&i.WaitingStartedAt,
		&i.AccumulatedWaitingSeconds,
		&i.MatchesPlayed,
		&i.Wins,
		&i.Losses,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countWaitingSessionPlayers = `-- name: CountWaitingSessionPlayers :one
SELECT count(*) FROM session_players WHERE session_id = $1 AND status = 'WAITING'
`

// Read-only headcount used by the auto-fill background job to decide how
// many of a session's AVAILABLE courts it can fill this tick; the
// authoritative check happens inside GenerateAutomatic's own FOR UPDATE
// transaction.
func (q *Queries) CountWaitingSessionPlayers(ctx context.Context, sessionID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWaitingSessionPlayers, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCourt = `-- name: CreateCourt :one

INSERT INTO courts (session_id, name)
VALUES ($1, $2)
RETURNING id, session_id, name, status, created_at, updated_at
`

type CreateCourtParams struct {
	SessionID uuid.UUID `json:"session_id"`
	Name      string    `json:"name"`
}

// ============================================================
// Courts
// ============================================================
func (q *Queries) CreateCourt(ctx context.Context, arg CreateCourtParams) (Court, error) {
	row := q.db.QueryRow(ctx, createCourt, arg.SessionID, arg.Name)
	var i Court
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (club_id, name, assignment_mode)
VALUES ($1, $2, $3)
RETURNING id, club_id, name, status, assignment_mode, started_at, ended_at, created_at, updated_at, auto_fill_enabled
`

type CreateSessionParams struct {
	ClubID         uuid.UUID             `json:"club_id"`
	Name           string                `json:"name"`
	AssignmentMode SessionAssignmentMode `json:"assignment_mode"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.ClubID, arg.Name, arg.AssignmentMode)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Name,
		&i.Status,
		&i.AssignmentMode,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoFillEnabled,
	)
	return i, err
}

const endSession = `-- name: EndSession :one
UPDATE sessions
SET status = 'FINISHED', ended_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, club_id, name, status, assignment_mode, started_at, ended_at, created_at, updated_at, auto_fill_enabled
`

func (q *Queries) EndSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, endSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Name,
		&i.Status,
		&i.AssignmentMode,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoFillEnabled,
	)
	return i, err
}

const getCourtByID = `-- name: GetCourtByID :one
SELECT id, session_id, name, status, created_at, updated_at FROM courts WHERE id = $1
`

func (q *Queries) GetCourtByID(ctx context.Context, id uuid.UUID) (Court, error) {
	row := q.db.QueryRow(ctx, getCourtByID, id)
	var i Court
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, club_id, name, status, assignment_mode, started_at, ended_at, created_at, updated_at, auto_fill_enabled FROM sessions WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Name,
		&i.Status,
		&i.AssignmentMode,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoFillEnabled,
	)
	return i, err
}

const getSessionPlayer = `-- name: GetSessionPlayer :one
SELECT id, session_id, player_id, status, waiting_started_at, accumulated_waiting_seconds, matches_played, wins, losses, created_at, updated_at FROM session_players WHERE id = $1
`

func (q *Queries) GetSessionPlayer(ctx context.Context, id uuid.UUID) (SessionPlayer, error) {
	row := q.db.QueryRow(ctx, getSessionPlayer, id)
	var i SessionPlayer
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.PlayerID,
		&i.Status,
		&i.WaitingStartedAt,
		&i.AccumulatedWaitingSeconds,
		&i.MatchesPlayed,
		&i.Wins,
		&i.Losses,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionPlayerBySessionAndPlayer = `-- name: GetSessionPlayerBySessionAndPlayer :one
SELECT id, session_id, player_id, status, waiting_started_at, accumulated_waiting_seconds, matches_played, wins, losses, created_at, updated_at FROM session_players WHERE session_id = $1 AND player_id = $2::uuid
`

type GetSessionPlayerBySessionAndPlayerParams struct {
	SessionID uuid.UUID `json:"session_id"`
	PlayerID  uuid.UUID `json:"player_id"`
}

func (q *Queries) GetSessionPlayerBySessionAndPlayer(ctx context.Context, arg GetSessionPlayerBySessionAndPlayerParams) (SessionPlayer, error) {
	row := q.db.QueryRow(ctx, getSessionPlayerBySessionAndPlayer, arg.SessionID, arg.PlayerID)
	var i SessionPlayer
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.PlayerID,
		&i.Status,
		&i.WaitingStartedAt,
		&i.AccumulatedWaitingSeconds,
		&i.MatchesPlayed,
		&i.Wins,
		&i.Losses,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionPlayerBySessionAndPlayerForUpdate = `-- name: GetSessionPlayerBySessionAndPlayerForUpdate :one
SELECT id, session_id, player_id, status, waiting_started_at, accumulated_waiting_seconds, matches_played, wins, losses, created_at, updated_at FROM session_players WHERE session_id = $1 AND player_id = $2::uuid FOR UPDATE
`

type GetSessionPlayerBySessionAndPlayerForUpdateParams struct {
	SessionID uuid.UUID `json:"session_id"`
	PlayerID  uuid.UUID `json:"player_id"`
}

func (q *Queries) GetSessionPlayerBySessionAndPlayerForUpdate(ctx context.Context, arg GetSessionPlayerBySessionAndPlayerForUpdateParams) (SessionPlayer, error) {
	row := q.db.QueryRow(ctx, getSessionPlayerBySessionAndPlayerForUpdate, arg.SessionID, arg.PlayerID)
	var i SessionPlayer
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.PlayerID,
		&i.Status,
		&i.WaitingStartedAt,
		&i.AccumulatedWaitingSeconds,
		&i.MatchesPlayed,
		&i.Wins,
		&i.Losses,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementSessionPlayerMatchStats = `-- name: IncrementSessionPlayerMatchStats :one
UPDATE session_players
SET matches_played = matches_played + 1,
    wins = wins + $2,
    losses = losses + $3,
    updated_at = now()
WHERE id = $1
RETURNING id, session_id, player_id, status, waiting_started_at, accumulated_waiting_seconds, matches_played, wins, losses, created_at, updated_at
`

type IncrementSessionPlayerMatchStatsParams struct {
	ID     uuid.UUID `json:"id"`
	Wins   int32     `json:"wins"`
	Losses int32     `json:"losses"`
}

func (q *Queries) IncrementSessionPlayerMatchStats(ctx context.Context, arg IncrementSessionPlayerMatchStatsParams) (SessionPlayer, error) {
	row := q.db.QueryRow(ctx, incrementSessionPlayerMatchStats, arg.ID, arg.Wins, arg.Losses)
	var i SessionPlayer
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.PlayerID,
		&i.Status,
		&i.WaitingStartedAt,
		&i.AccumulatedWaitingSeconds,
		&i.MatchesPlayed,
		&i.Wins,
		&i.Losses,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveAutoFillSessions = `-- name: ListActiveAutoFillSessions :many
SELECT id, club_id, name, status, assignment_mode, started_at, ended_at, created_at, updated_at, auto_fill_enabled FROM sessions
WHERE status = 'ACTIVE' AND assignment_mode = 'AUTOMATIC' AND auto_fill_enabled = true
ORDER BY created_at
`

// Sessions eligible for the fully-automatic auto-fill background job: ACTIVE,
// AUTOMATIC assignment, and auto_fill_enabled. Read-only (no locking) — the
// job's per-session coordination lock and match.Service.GenerateAutomatic's
// own transactional locking handle correctness.
func (q *Queries) ListActiveAutoFillSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.Query(ctx, listActiveAutoFillSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.Name,
			&i.Status,
			&i.AssignmentMode,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AutoFillEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailableCourtsBySession = `-- name: ListAvailableCourtsBySession :many
SELECT id, session_id, name, status, created_at, updated_at FROM courts WHERE session_id = $1 AND status = 'AVAILABLE' ORDER BY name
`

func (q *Queries) ListAvailableCourtsBySession(ctx context.Context, sessionID uuid.UUID) ([]Court, error) {
	rows, err := q.db.Query(ctx, listAvailableCourtsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Court{}
	for rows.Next() {
		var i Court
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourtsBySession = `-- name: ListCourtsBySession :many
SELECT id, session_id, name, status, created_at, updated_at FROM courts WHERE session_id = $1 ORDER BY name
`

func (q *Queries) ListCourtsBySession(ctx context.Context, sessionID uuid.UUID) ([]Court, error) {
	rows, err := q.db.Query(ctx, listCourtsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Court{}
	for rows.Next() {
		var i Court
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionPlayers = `-- name: ListSessionPlayers :many
SELECT id, session_id, player_id, status, waiting_started_at, accumulated_waiting_seconds, matches_played, wins, losses, created_at, updated_at FROM session_players WHERE session_id = $1 ORDER BY created_at
`

func (q *Queries) ListSessionPlayers(ctx context.Context, sessionID uuid.UUID) ([]SessionPlayer, error) {
	rows, err := q.db.Query(ctx, listSessionPlayers, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionPlayer{}
	for rows.Next() {
		var i SessionPlayer
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.PlayerID,
			&i.Status,
			&i.WaitingStartedAt,
			&i.AccumulatedWaitingSeconds,
			&i.MatchesPlayed,
			&i.Wins,
			&i.Losses,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByClub = `-- name: ListSessionsByClub :many
SELECT id, club_id, name, status, assignment_mode, started_at, ended_at, created_at, updated_at, auto_fill_enabled FROM sessions WHERE club_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListSessionsByClub(ctx context.Context, clubID uuid.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByClub, clubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.Name,
			&i.Status,
			&i.AssignmentMode,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AutoFillEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaitingSessionPlayersForUpdate = `-- name: ListWaitingSessionPlayersForUpdate :many
SELECT id, session_id, player_id, status, waiting_started_at, accumulated_waiting_seconds, matches_played, wins, losses, created_at, updated_at FROM session_players
WHERE session_id = $1 AND status = 'WAITING'
ORDER BY player_id
FOR UPDATE
`

// Eligible players for matchmaking, locked to serialize concurrent match generation.
func (q *Queries) ListWaitingSessionPlayersForUpdate(ctx context.Context, sessionID uuid.UUID) ([]SessionPlayer, error) {
	rows, err := q.db.Query(ctx, listWaitingSessionPlayersForUpdate, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionPlayer{}
	for rows.Next() {
		var i SessionPlayer
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.PlayerID,
			&i.Status,
			&i.WaitingStartedAt,
			&i.AccumulatedWaitingSeconds,
			&i.MatchesPlayed,
			&i.Wins,
			&i.Losses,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAvailableCourtForUpdate = `-- name: LockAvailableCourtForUpdate :one
SELECT id, session_id, name, status, created_at, updated_at FROM courts
WHERE id = $1 AND status = 'AVAILABLE'
FOR UPDATE
`

func (q *Queries) LockAvailableCourtForUpdate(ctx context.Context, id uuid.UUID) (Court, error) {
	row := q.db.QueryRow(ctx, lockAvailableCourtForUpdate, id)
	var i Court
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockCourtByID = `-- name: LockCourtByID :one
SELECT id, session_id, name, status, created_at, updated_at FROM courts WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockCourtByID(ctx context.Context, id uuid.UUID) (Court, error) {
	row := q.db.QueryRow(ctx, lockCourtByID, id)
	var i Court
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockSessionByID = `-- name: LockSessionByID :one
SELECT id, club_id, name, status, assignment_mode, started_at, ended_at, created_at, updated_at, auto_fill_enabled FROM sessions WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockSessionByID(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, lockSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Name,
		&i.Status,
		&i.AssignmentMode,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoFillEnabled,
	)
	return i, err
}

const lockSessionPlayersByIDs = `-- name: LockSessionPlayersByIDs :many
SELECT id, session_id, player_id, status, waiting_started_at, accumulated_waiting_seconds, matches_played, wins, losses, created_at, updated_at FROM session_players
WHERE id = ANY($1::uuid[])
ORDER BY id
FOR UPDATE
`

func (q *Queries) LockSessionPlayersByIDs(ctx context.Context, ids []uuid.UUID) ([]SessionPlayer, error) {
	rows, err := q.db.Query(ctx, lockSessionPlayersByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionPlayer{}
	for rows.Next() {
		var i SessionPlayer
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.PlayerID,
			&i.Status,
			&i.WaitingStartedAt,
			&i.AccumulatedWaitingSeconds,
			&i.MatchesPlayed,
			&i.Wins,
			&i.Losses,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCourtStatus = `-- name: SetCourtStatus :one
UPDATE courts SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, session_id, name, status, created_at, updated_at
`

type SetCourtStatusParams struct {
	ID     uuid.UUID   `json:"id"`
	Status CourtStatus `json:"status"`
}

func (q *Queries) SetCourtStatus(ctx context.Context, arg SetCourtStatusParams) (Court, error) {
	row := q.db.QueryRow(ctx, setCourtStatus, arg.ID, arg.Status)
	var i Court
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setSessionPlayerStatus = `-- name: SetSessionPlayerStatus :one
UPDATE session_players
SET status = $2,
    waiting_started_at = CASE WHEN $2::session_player_status = 'WAITING' THEN now() ELSE waiting_started_at END,
    accumulated_waiting_seconds = CASE
        WHEN status = 'WAITING' AND $2::session_player_status != 'WAITING'
            THEN accumulated_waiting_seconds + GREATEST(0, EXTRACT(EPOCH FROM (now() - waiting_started_at))::bigint)
        ELSE accumulated_waiting_seconds
    END,
    updated_at = now()
WHERE id = $1
RETURNING id, session_id, player_id, status, waiting_started_at, accumulated_waiting_seconds, matches_played, wins, losses, created_at, updated_at
`

type SetSessionPlayerStatusParams struct {
	ID     uuid.UUID           `json:"id"`
	Status SessionPlayerStatus `json:"status"`
}

func (q *Queries) SetSessionPlayerStatus(ctx context.Context, arg SetSessionPlayerStatusParams) (SessionPlayer, error) {
	row := q.db.QueryRow(ctx, setSessionPlayerStatus, arg.ID, arg.Status)
	var i SessionPlayer
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.PlayerID,
		&i.Status,
		&i.WaitingStartedAt,
		&i.AccumulatedWaitingSeconds,
		&i.MatchesPlayed,
		&i.Wins,
		&i.Losses,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const startSession = `-- name: StartSession :one
UPDATE sessions
SET status = 'ACTIVE', started_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, club_id, name, status, assignment_mode, started_at, ended_at, created_at, updated_at, auto_fill_enabled
`

func (q *Queries) StartSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, startSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Name,
		&i.Status,
		&i.AssignmentMode,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoFillEnabled,
	)
	return i, err
}

const updateSessionAssignmentMode = `-- name: UpdateSessionAssignmentMode :one
UPDATE sessions
SET assignment_mode = $2, updated_at = now()
WHERE id = $1
RETURNING id, club_id, name, status, assignment_mode, started_at, ended_at, created_at, updated_at, auto_fill_enabled
`

type UpdateSessionAssignmentModeParams struct {
	ID             uuid.UUID             `json:"id"`
	AssignmentMode SessionAssignmentMode `json:"assignment_mode"`
}

func (q *Queries) UpdateSessionAssignmentMode(ctx context.Context, arg UpdateSessionAssignmentModeParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSessionAssignmentMode, arg.ID, arg.AssignmentMode)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Name,
		&i.Status,
		&i.AssignmentMode,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoFillEnabled,
	)
	return i, err
}

const updateSessionAutoFillEnabled = `-- name: UpdateSessionAutoFillEnabled :one
UPDATE sessions
SET auto_fill_enabled = $2, updated_at = now()
WHERE id = $1
RETURNING id, club_id, name, status, assignment_mode, started_at, ended_at, created_at, updated_at, auto_fill_enabled
`

type UpdateSessionAutoFillEnabledParams struct {
	ID              uuid.UUID `json:"id"`
	AutoFillEnabled bool      `json:"auto_fill_enabled"`
}

func (q *Queries) UpdateSessionAutoFillEnabled(ctx context.Context, arg UpdateSessionAutoFillEnabledParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSessionAutoFillEnabled, arg.ID, arg.AutoFillEnabled)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Name,
		&i.Status,
		&i.AssignmentMode,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoFillEnabled,
	)
	return i, err
}
